baseURL = "http://beta.finotto.io/"
languageCode = "en-us"
title = "Michele Finotto"
theme = "hyde"

[params]
themeColor = "theme-base-finotto"
description = "Containerized backend developer. Gopher with a knack for rubies."
